#!/bin/bash

export DISPLAY=${DISPLAY:-:0}
melt -verbose -profile square_pal green.mlt out=22299 -filter webvfx:dynamic-filter.html out=22299 -consumer sdl -consumer avformat:tcp://localhost:1111?pkt_size=1316\&reuse=1 real_time=1 terminate_on_pause=0 f=webm vcodec=libvpx b=1000k s=720x570 acodec=libvorbis ab=128k
